### ISSUE TITLE
Installing pytest-html corrupting existing pytest.

### ISSUE THREAD

**Issue by jayant2014** [pytest-dev/pytest-html#137]
I had pytest module already installed. Then I installed pytest-html using pip. Then I could see pytest is corrupted. This used to work earlier.

```
# pytest --help
usage: pytest [options] [file_or_dir] [file_or_dir] [...]

# pip install pytest-html
Collecting pytest-html
  Using cached pytest_html-1.16.0-py2.py3-none-any.whl
Collecting pytest-metadata (from pytest-html)
  Using cached pytest_metadata-1.5.0-py2.py3-none-any.whl
Requirement already satisfied: pytest>=3.0 in /usr/lib/python2.7/site-packages (from pytest-html)
Requirement already satisfied: pluggy<0.7,>=0.5 in /usr/lib/python2.7/site-packages (from pytest>=3.0->pytest-html)
Requirement already satisfied: attrs>=17.2.0 in /usr/lib/python2.7/site-packages (from pytest>=3.0->pytest-html)
Requirement already satisfied: funcsigs; python_version < "3.0" in /usr/lib/python2.7/site-packages (from pytest>=3.0->pytest-html)
Requirement already satisfied: py>=1.5.0 in /usr/lib/python2.7/site-packages (from pytest>=3.0->pytest-html)
Requirement already satisfied: setuptools in /usr/lib/python2.7/site-packages (from pytest>=3.0->pytest-html)
Requirement already satisfied: six>=1.10.0 in /usr/lib/python2.7/site-packages (from pytest>=3.0->pytest-html)
Installing collected packages: pytest-metadata, pytest-html
Successfully installed pytest-html-1.16.0 pytest-metadata-1.5.0

# pytest --help
Traceback (most recent call last):
  File "/usr/bin/pytest", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/_pytest/config.py", line 50, in main
    config = _prepareconfig(args, plugins)
  File "/usr/lib/python2.7/site-packages/_pytest/config.py", line 160, in _prepareconfig
    pluginmanager=pluginmanager, args=args)
  File "/usr/lib/python2.7/site-packages/pluggy/__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/usr/lib/python2.7/site-packages/pluggy/__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/lib/python2.7/site-packages/pluggy/__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "/usr/lib/python2.7/site-packages/pluggy/callers.py", line 196, in _multicall
    gen.send(outcome)
  File "/usr/lib/python2.7/site-packages/_pytest/helpconfig.py", line 68, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/usr/lib/python2.7/site-packages/pluggy/callers.py", line 77, in get_result
    _reraise(*ex)  # noqa
  File "/usr/lib/python2.7/site-packages/pluggy/callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "/usr/lib/python2.7/site-packages/_pytest/config.py", line 942, in pytest_cmdline_parse
    self.parse(args)
  File "/usr/lib/python2.7/site-packages/_pytest/config.py", line 1107, in parse
    self._preparse(args, addopts=addopts)
  File "/usr/lib/python2.7/site-packages/_pytest/config.py", line 1070, in _preparse
    self.pluginmanager.load_setuptools_entrypoints('pytest11')
  File "/usr/lib/python2.7/site-packages/pluggy/__init__.py", line 397, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2405, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2411, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/_pytest/assertion/rewrite.py", line 212, in load_module
    py.builtin.exec_(co, mod.__dict__)
  File "/usr/lib/python2.7/site-packages/py/_builtin.py", line 221, in exec_
    exec2(obj, globals, locals)
  File "<string>", line 7, in exec2
  File "/usr/lib/python2.7/site-packages/pytest_metadata/plugin.py", line 8, in <module>
    import _pytest._pluggy as pluggy
ImportError: No module named _pluggy
```

I could reintsall pytest by clearing the corrupted one, but never use pytest-html after this.

Following are version info.

```
# python --version
Python 2.7.5
# pytest --version
This is pytest version 3.3.0, imported from /usr/lib/python2.7/site-packages/pytest.pyc_
```

**Comment by RonnyPfannschmidt** [comment]
the pytest_metadata plugin iunadvertedly uses a private api, thats a bug in pytest_metadata

**Comment by RonnyPfannschmidt** [comment]
this is davehunt/pytest-metadata#5

**Comment by jayant2014** [comment]
Thanks Ronny got it.
