### ISSUE TITLE
pytest-html breaks on pytest 3.3.0

### ISSUE THREAD

**Issue by henklaak** [pytest-dev/pytest-html#139]
```
(C:\Localdata\anaconda2) C:\Users\hlaak\Documents>conda list pytest*
# packages in environment at C:\Localdata\anaconda2:
#
pytest                    3.3.0            py27h0d7acca_0
pytest-benchmark          3.0.0                    py27_1    conda-forge
pytest-cache              1.0                      py27_0
pytest-cov                2.5.1            py27h9534814_0
pytest-forked             0.2              py27h4ba30fc_0
pytest-html               1.16.0                   py27_0    conda-forge
pytest-metadata           1.5.0                    py27_0    conda-forge
pytest-mpl                0.9                        py_0    conda-forge
pytest-qt                 2.3.0                      py_0    conda-forge
pytest-runner             3.0              py27h718ee88_0
pytest-timeout            1.2.1            py27h7ab0233_0
pytest-xdist              1.20.1           py27h4d48a95_0

(C:\Localdata\anaconda2) C:\Users\hlaak\Documents>
```

```
(C:\Localdata\anaconda2) C:\Users\hlaak\Documents>pytest
Traceback (most recent call last):
  File "C:\Localdata\anaconda2\Scripts\pytest-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Localdata\anaconda2\lib\site-packages\_pytest\config.py", line 50, in main
    config = _prepareconfig(args, plugins)
  File "C:\Localdata\anaconda2\lib\site-packages\_pytest\config.py", line 160, in _prepareconfig
    pluginmanager=pluginmanager, args=args)
  File "C:\Localdata\anaconda2\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "C:\Localdata\anaconda2\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Localdata\anaconda2\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "C:\Localdata\anaconda2\lib\site-packages\pluggy\callers.py", line 196, in _multicall
    gen.send(outcome)
  File "C:\Localdata\anaconda2\lib\site-packages\_pytest\helpconfig.py", line 68, in pytest_cmdline_parse
    config = outcome.get_result()
  File "C:\Localdata\anaconda2\lib\site-packages\pluggy\callers.py", line 77, in get_result
    _reraise(*ex)  # noqa
  File "C:\Localdata\anaconda2\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "C:\Localdata\anaconda2\lib\site-packages\_pytest\config.py", line 942, in pytest_cmdline_parse
    self.parse(args)
  File "C:\Localdata\anaconda2\lib\site-packages\_pytest\config.py", line 1107, in parse
    self._preparse(args, addopts=addopts)
  File "C:\Localdata\anaconda2\lib\site-packages\_pytest\config.py", line 1070, in _preparse
    self.pluginmanager.load_setuptools_entrypoints('pytest11')
  File "C:\Localdata\anaconda2\lib\site-packages\pluggy\__init__.py", line 397, in load_setuptools_entrypoints
    plugin = ep.load()
  File "C:\Localdata\anaconda2\lib\site-packages\pkg_resources\__init__.py", line 2405, in load
    return self.resolve()
  File "C:\Localdata\anaconda2\lib\site-packages\pkg_resources\__init__.py", line 2411, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "C:\Localdata\anaconda2\lib\site-packages\_pytest\assertion\rewrite.py", line 212, in load_module
    py.builtin.exec_(co, mod.__dict__)
  File "C:\Localdata\anaconda2\lib\site-packages\py\_builtin.py", line 221, in exec_
    exec2(obj, globals, locals)
  File "<string>", line 7, in exec2
  File "C:\Localdata\anaconda2\lib\site-packages\pytest_metadata\plugin.py", line 8, in <module>
    import _pytest._pluggy as pluggy
ImportError: No module named _pluggy
```

**Comment by henklaak** [comment]
Never mind. My pytest-metadata was out of date. 1.5.1 solves it.

**Comment by nicoddemus** [comment]
Yep, was about to comment about that. I opened conda-forge/pytest-metadata-feedstock#1 to update the conda package.

**Comment by nicoddemus** [comment]
@henklaak the `1.5.1` package is [now available](https://anaconda.org/conda-forge/pytest-metadata/files). 👍

**Comment by henklaak** [comment]
Awesome 👍
