### ISSUE TITLE
Encounter memory error when run test  concurrently for a long time

### ISSUE THREAD

**Issue by hdw868** [pytest-dev/pytest-html#225]
encounter following error when running pytest-html with pytest-xdist repeatedly for about 300-500 times.

```
pytest tests\test_user12.py --count=500 -n=10 --headless
======== test session starts =======
platform win32 -- Python 3.7.3, pytest-4.4.0, py-1.8.0, pluggy-0.9.0 -- c:\python37\python.exe
cachedir: .pytest_cache
metadata: {'Python': '3.7.3', 'Platform': 'Windows-10-10.0.14393-SP0', 'Packages': {'pytest': '4.4.0', 'py': '1.8.0', 'pluggy': '0.9.0'}, 'Plugins': {'xdist': '1.29.0', 'variables': '1.7.1', 'repeat': '0.8.0', 'metadata': '1.8.0', 'json': '0.4.0', 'json-report': '1.1.0', 'html': '1.20.0', 'forked': '1.0.2', 'cov': '2.7.1', 'aggreport': '0.1.4'}, 'Yaml Config Path': 'C:\\Dev\\test_persona\\config.yaml'}
rootdir: C:\Dev\test_persona\tests, inifile: pytest.ini
plugins: xdist-1.29.0, variables-1.7.1, repeat-0.8.0, metadata-1.8.0, json-0.4.0, json-report-1.1.0, html-1.20.0, forked-1.0.2, cov-2.7.1, aggreport-0.1.4
...

[gw2] FAILED tests\test_user12.py::TestUSR012::test_export_bar_chart[383-500]
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "c:\python37\lib\site-packages\_pytest\main.py", line 209, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "c:\python37\lib\site-packages\_pytest\main.py", line 249, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "c:\python37\lib\site-packages\pluggy\hooks.py", line 289, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "c:\python37\lib\site-packages\pluggy\manager.py", line 68, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "c:\python37\lib\site-packages\pluggy\manager.py", line 62, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "c:\python37\lib\site-packages\pluggy\callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "c:\python37\lib\site-packages\pluggy\callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "c:\python37\lib\site-packages\pluggy\callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "c:\python37\lib\site-packages\xdist\dsession.py", line 115, in pytest_runtestloop
INTERNALERROR>     self.loop_once()
INTERNALERROR>   File "c:\python37\lib\site-packages\xdist\dsession.py", line 138, in loop_once
INTERNALERROR>     call(**kwargs)
INTERNALERROR>   File "c:\python37\lib\site-packages\xdist\dsession.py", line 257, in worker_testreport
INTERNALERROR>     self.config.hook.pytest_runtest_logreport(report=rep)
INTERNALERROR>   File "c:\python37\lib\site-packages\pluggy\hooks.py", line 289, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "c:\python37\lib\site-packages\pluggy\manager.py", line 68, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "c:\python37\lib\site-packages\pluggy\manager.py", line 62, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "c:\python37\lib\site-packages\pluggy\callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "c:\python37\lib\site-packages\pluggy\callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "c:\python37\lib\site-packages\pluggy\callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "c:\python37\lib\site-packages\pytest_html\plugin.py", line 504, in pytest_runtest_logreport
INTERNALERROR>     self.append_failed(report)
INTERNALERROR>   File "c:\python37\lib\site-packages\pytest_html\plugin.py", line 294, in append_failed
INTERNALERROR>     self._appendrow('Failed', report)
INTERNALERROR>   File "c:\python37\lib\site-packages\pytest_html\plugin.py", line 266, in _appendrow
INTERNALERROR>     result = self.TestResult(outcome, report, self.logfile, self.config)
INTERNALERROR>   File "c:\python37\lib\site-packages\pytest_html\plugin.py", line 119, in __init__
INTERNALERROR>     self.append_extra_html(extra, extra_index, test_index)
INTERNALERROR>   File "c:\python37\lib\site-packages\pytest_html\plugin.py", line 218, in append_extra_html
INTERNALERROR>     href = data_uri(content)
INTERNALERROR>   File "c:\python37\lib\site-packages\pytest_html\plugin.py", line 82, in data_uri
INTERNALERROR>     data = b64encode(content.encode(charset)).decode('ascii')
INTERNALERROR> MemoryError
```
Please let me know if more message if needed.
**I do not have this problem if I run it in a single process, I think it has something to do with pytest-xdist as well.**

**Comment by BeyondEvil** [comment]
I have no idea what's going on here... :( 

But I know some smart people that might have one: @nicoddemus  @RonnyPfannschmidt

**Comment by nicoddemus** [comment]
It seems @hdw868 is running out of memory. Please use your task manager to see how much memory your computer is using when running with xdist; I'm fairly certain you are reaching the limit of your computer. 

When you execute `python`, the banner shows if you are in a 32bit or 64bit system:

```
λ python
Python 3.6.7 (default, Jul  2 2019, 02:21:41) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

You should check that as well.

**Comment by hdw868** [comment]
@nicoddemus Thanks, I think it is because I use headless mode chrome. According to this [article ](https://docs.browserless.io/blog/2018/06/04/puppeteer-best-practices.html) and per my observation,  and it turns out that headless chrome exhausted all my system memory after long time running. Thanks for your help!
