### ISSUE TITLE
Getting KeyError time when trying to generate report

### ISSUE THREAD

**Issue by eblis** [pytest-dev/pytest-html#290]
I'm trying to run the following command `pipenv run py.test --html=report.html --html-profiling --html-call-graph` but getting an internal error.

```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "project_venv\lib\site-packages\_pytest\main.py", line 191, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "project_venv\lib\site-packages\_pytest\main.py", line 247, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "project_venv\lib\site-packages\pluggy\hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "project_venv\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "project_venv\lib\site-packages\pluggy\manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "project_venv\lib\site-packages\pluggy\callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "project_venv\lib\site-packages\pluggy\callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "project_venv\lib\site-packages\pluggy\callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "project_venv\lib\site-packages\_pytest\main.py", line 272, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "project_venv\lib\site-packages\pluggy\hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "project_venv\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "project_venv\lib\site-packages\pluggy\manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "project_venv\lib\site-packages\pluggy\callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "project_venv\lib\site-packages\pluggy\callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "project_venv\lib\site-packages\pluggy\callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "project_venv\lib\site-packages\_pytest\runner.py", line 85, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "project_venv\lib\site-packages\_pytest\runner.py", line 100, in runtestprotocol
INTERNALERROR>     reports.append(call_and_report(item, "call", log))
INTERNALERROR>   File "project_venv\lib\site-packages\_pytest\runner.py", line 188, in call_and_report
INTERNALERROR>     report = hook.pytest_runtest_makereport(item=item, call=call)
INTERNALERROR>   File "project_venv\lib\site-packages\pluggy\hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "project_venv\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "project_venv\lib\site-packages\pluggy\manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "project_venv\lib\site-packages\pluggy\callers.py", line 203, in _multicall
INTERNALERROR>     gen.send(outcome)
INTERNALERROR>   File "project_venv\lib\site-packages\pytest_html_profiling\profiling_plugin.py", line 159, in pytest_runtest_makereport
INTERNALERROR>     prof_result = self.profs_results[item.name][stat]
INTERNALERROR> KeyError: 'time'
```

**Comment by BeyondEvil** [comment]
It looks like you're using a [fork](https://github.com/hyperbrowser/pytest-html-profiling) of this plugin. Can you reproduce this with the "real" plugin?

If so, it would be great if you could share a minimal test case that reproduces the issue.

At the very least you should provide more information, like what OS are you using, python, pytest and plugin versions. Does it happen locally and/or in CI? etc.

**Comment by eblis** [comment]
Ah, sorry, I thought I was writing the issue in that repo :)
Sorry.
I'll try to report this on their repository, but since you asked i'll add the data here as well.
Any pytest-bdd test fails with the above error.

My dependencies are
```
APScheduler==3.6.3
atomicwrites==1.3.0
attrs==19.3.0
certifi==2020.4.5.1
chardet==3.0.4
colorama==0.4.3
coloredlogs==14.0
configobj==5.0.6
cx-Oracle==7.3.0
dataclasses-json==0.4.2
decorator==4.4.2
glob2==0.7
gprof2dot==2019.11.30
humanfriendly==8.1
idna==2.9
influxdb==5.2.3
Mako==1.1.2
MarkupSafe==1.1.1
marshmallow==3.5.1
marshmallow-enum==1.5.1
marshmallow-sqlalchemy==0.22.3
mongoengine==0.18.2
more-itertools==8.2.0
mypy-extensions==0.4.3
packaging==20.3
pamqp==2.3.0
parse==1.15.0
parse-type==0.5.2
petpcomms==0.1.6
petpmvcs==0.1.24
pinject==0.15.dev3
pluggy==0.13.1
py==1.8.1
py-cpuinfo==5.0.0
pyaml==20.4.0
pygraphviz==1.5
pymongo==3.8.0
pyparsing==3.0.0a1
pyreadline==2.1
pytest==5.4.1
pytest-bdd==3.2.1
pytest-benchmark==3.2.3
pytest-html-profiling==1.0.0
pytest-metadata==1.8.0
pytest-mock==3.0.0
python-dateutil==2.8.1
pytz==2019.3
PyYAML==5.3.1
rabbitpy==2.0.1
requests==2.23.0
six==1.14.0
SQLAlchemy==1.3.15
stringcase==1.2.0
typing-extensions==3.7.4.2
typing-inspect==0.5.0
tzlocal==2.1b1
urllib3==1.25.8
wcwidth==0.1.9
```
Python version 3.8.1 x64 on Windows 10 x64 with pipenv version 2018.11.26

**Comment by gnikonorov** [comment]
Hi @eblis were you able to reproduce your issue with this plugin instead of [pytest-html-profiling](https://github.com/hyperbrowser/pytest-html-profiling)?

**Comment by eblis** [comment]
I couldn't reproduce with this command: `pipenv run py.test --html=report.html --self-contained-html`
