### ISSUE TITLE
When using pytest-html with pytest-xdist plugin , i am getting the "assert not crashitem, (crashitem, node)

### ISSUE THREAD

**Issue by pranav165** [pytest-dev/pytest-html#297]
Exception is thrown at getplugin statement

@pytest.hookimpl(hookwrapper=True)
def pytest_runtest_makereport(item):
    pytest_html = item.config.pluginmanager.getplugin("html")

scheduling tests via LoadScheduling

tests/api/test_price_book.py::TestPriceBookAPI::test_get_pricebook_id 
tests/api/test_price_book.py::TestPriceBookAPI::test_get_pricebook_api 
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "C:\Users\pranavsh\OneDrive - Ciena Corporation\Desktop\e2e\networkplanner-e2e-test\venv\lib\site-packages\_pytest\main.py", line 191, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "C:\Users\pranavsh\OneDrive - Ciena Corporation\Desktop\e2e\networkplanner-e2e-test\venv\lib\site-packages\_pytest\main.py", line 247, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "C:\Users\pranavsh\OneDrive - Ciena Corporation\Desktop\e2e\networkplanner-e2e-test\venv\lib\site-packages\pluggy\hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "C:\Users\pranavsh\OneDrive - Ciena Corporation\Desktop\e2e\networkplanner-e2e-test\venv\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "C:\Users\pranavsh\OneDrive - Ciena Corporation\Desktop\e2e\networkplanner-e2e-test\venv\lib\site-packages\pluggy\manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "C:\Users\pranavsh\OneDrive - Ciena Corporation\Desktop\e2e\networkplanner-e2e-test\venv\lib\site-packages\pluggy\callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "C:\Users\pranavsh\OneDrive - Ciena Corporation\Desktop\e2e\networkplanner-e2e-test\venv\lib\site-packages\pluggy\callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "C:\Users\pranavsh\OneDrive - Ciena Corporation\Desktop\e2e\networkplanner-e2e-test\venv\lib\site-packages\pluggy\callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "c:\users\pranavsh\onedrive - ciena corporation\desktop\e2e\networkplanner-e2e-test\venv\lib\site-packages\xdist\dsession.py", line 112, in pytest_runtestloop
INTERNALERROR>     self.loop_once()
INTERNALERROR>   File "c:\users\pranavsh\onedrive - ciena corporation\desktop\e2e\networkplanner-e2e-test\venv\lib\site-packages\xdist\dsession.py", line 135, in loop_once
INTERNALERROR>     call(**kwargs)
INTERNALERROR>   File "c:\users\pranavsh\onedrive - ciena corporation\desktop\e2e\networkplanner-e2e-test\venv\lib\site-packages\xdist\dsession.py", line 177, in worker_workerfinished
INTERNALERROR>     assert not crashitem, (crashitem, node)
INTERNALERROR> AssertionError: ('tests/api/test_price_book.py::TestPriceBookAPI::test_get_pricebook_id', <WorkerController gw1>)
INTERNALERROR> assert not 'tests/api/test_price_book.py::TestPriceBookAPI::test_get_pricebook_id'
Traceback (most recent call last):
  File "C:/Users/pranavsh/OneDrive - Ciena Corporation/Desktop/e2e/networkplanner-e2e-test/main.py", line 23, in <module>
    main(sys.argv[1:])
  File "C:/Users/pranavsh/OneDrive - Ciena Corporation/Desktop/e2e/networkplanner-e2e-test/main.py", line 19, in main
    raise Exception("Test Execution Failed with exit code {}".format(exit_code))
Exception: Test Execution Failed with exit code 3

metadata: {'Python': '3.8.1', 'Platform': 'Windows-10-10.0.18362-SP0', 'Packages': {'pytest': '5.4.1', 'py': '1.8.1', 'pluggy': '0.13.1'}, 'Plugins': {'flaky': '3.6.1', 'forked': '1.1.3', 'html': '2.1.1', 'metadata': '1.9.0', 'xdist': '1.32.0'}, 'channelplanner': '1.5.1-9-cicd', 'mbfsimulation': '2.0.0-10-cicd', 'platform': '19.10.01', 'oneple': '2.69.0-cicd', 'plannerplus': '1.2.0-322-cicd', 'appscore': '3.11.2-cicd', 'env': 'cicd', 'average_api_response_time (ms)': {'post /tokens': 2435, 'get /solutions/states': 2717}, 'average_ui_response_time (seconds)': {}}

plugins: flaky-3.6.1, forked-1.1.3, html-2.1.1, metadata-1.9.0, xdist-1.32.0

**Comment by pranav165** [comment]
Closing , as fixed by removing statements [report.path = report.nodeid.split('/')[-1].split('::')[0]
    report.nodeid = report.nodeid.split("::")[-1]]

@pytest.mark.hookwrapper
def pytest_runtest_makereport(item):
    pytest_html = item.config.pluginmanager.getplugin("html")
    outcome = yield
    report = outcome.get_result()
    report.path = report.nodeid.split('/')[-1].split('::')[0]
    report.nodeid = report.nodeid.split("::")[-1]
    report.description = getattr(item.obj, '__doc__')
