### ISSUE TITLE
AttributeError: 'Config' object has no attribute '_metadata' when using pytest_configure

### ISSUE THREAD

**Issue by LeiYangGH** [pytest-dev/pytest-html#500]
I follow the [doc](https://pytest-html.readthedocs.io/en/latest/user_guide.html#environment)

```python
def pytest_configure(config):
    config._metadata["foo"] = "bar"
```

When run it gives me error

> (tts) PS C:\GL\ncs\tts\onecloud2.0\qa\tts-appserver-ct> pytest test.py --html=report.html --self-contained-html
> INTERNALERROR> Traceback (most recent call last):
> INTERNALERROR>   File "C:\pv\tts\lib\site-packages\_pytest\main.py", line 264, in wrap_session
> INTERNALERROR>     config._do_configure()
> INTERNALERROR>   File "C:\pv\tts\lib\site-packages\_pytest\config\__init__.py", line 992, in _do_configure
> INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
> INTERNALERROR>   File "C:\pv\tts\lib\site-packages\pluggy\_hooks.py", line 277, in call_historic
> INTERNALERROR>     res = self._hookexec(self.name, self.get_hookimpls(), kwargs, False)
> INTERNALERROR>   File "C:\pv\tts\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
> INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
> INTERNALERROR>   File "C:\pv\tts\lib\site-packages\pluggy\_callers.py", line 60, in _multicall
> INTERNALERROR>     return outcome.get_result()
> INTERNALERROR>   File "C:\pv\tts\lib\site-packages\pluggy\_result.py", line 60, in get_result
> INTERNALERROR>     raise ex[1].with_traceback(ex[2])
> INTERNALERROR>   File "C:\pv\tts\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
> INTERNALERROR>     res = hook_impl.function(*args)
> INTERNALERROR>   File "C:\GL\ncs\tts\onecloud2.0\qa\tts-appserver-ct\conftest.py", line 15, in pytest_configure
> INTERNALERROR>     config._metadata["host"] = os.environ.get('IPPORT', None)

**Comment by LeiYangGH** [comment]
Worked after removing `@pytest.hookimpl(tryfirst=True)`
