### ISSUE TITLE
Wrong encoding of czech characters with diacritics in test names in HTML report

### ISSUE THREAD

**Issue by freetomik** [pytest-dev/pytest-html#581]
Hello,
I want to have czech characters with diacritics in test names, so I have disabled unicode characters escaping in `pytest.ini` with option `disable_test_id_escaping_and_forfeit_all_rights_to_community_support = True`, which is documented [here](https://docs.pytest.org/en/stable/how-to/parametrize.html#pytest-mark-parametrize-parametrizing-test-functions). In current version 3.2.0 there is a problem #559, which with [patch](https://github.com/pytest-dev/pytest-html/issues/559#issuecomment-1305181693) mentioned by @jfthuong I got to overcome. But still in html report I have wrong encoding in test names. Note, that in details encoding is correct.
I am on Windows 10 Pro 22H2 with Python 3.11.0 and pytest 7.2.1.
Any help or advice appreciated.

File `test_czech_encoding.py` with UTF-8 encoding:
```
import pytest

@pytest.mark.parametrize('czech_unicode_text', ['Loď čeří kýlem tůň obzvlášť v Grónské úžině.'])
def test_czech_encoding(czech_unicode_text):
    print(czech_unicode_text)
```
Pytest command (run from Windows Terminal with PowerShell 7.3.1):
`pytest --html=pytest_cz_enc_report.html --self-contained-html .\test_czech_encoding.py`

HTML report:
![obrazek](https://user-images.githubusercontent.com/5520368/213496750-d3805c9c-3398-45c7-8c50-c2d542988624.png)

**Comment by jfthuong** [comment]
How does the test id shows in terminal when you run with option `-v` or `-vv` ?

**Comment by freetomik** [comment]
In terminal test id shows correctly with verbose option.

**Comment by RonnyPfannschmidt** [comment]
i believe this relates to #583 and #559 duplicate ?

**Comment by nck974** [comment]
I'm having the same issue with every paramterized fixture used to test that is not uf8.

**Comment by BeyondEvil** [comment]
Do you mind testing if this is still an issue in the latest RC release? 4.0.0rc0

**Comment by freetomik** [comment]
I tried it, but I cannot test it, because with using the patch in `conftest.py` I am getting following error:
```
conftest.py:2: in <module>
    from pytest_html.html_report import HTMLReport
E   ModuleNotFoundError: No module named 'pytest_html.html_report'
```
`conftest.py`:
```
from pytest_html.html_report import HTMLReport

# temporary way to patch pytest-html to support non-ASCII characters 
# https://github.com/pytest-dev/pytest-html/issues/559#issuecomment-1305181693
def _save_report_patched(self, report_content):
    dir_name = self.logfile.parent
    assets_dir = dir_name / "assets"

    dir_name.mkdir(parents=True, exist_ok=True)
    if not self.self_contained:
        assets_dir.mkdir(parents=True, exist_ok=True)

    # ipdb.set_trace()
    self.logfile.write_text(report_content, encoding="utf-8")  # this line is modified 
    if not self.self_contained:
        style_path = assets_dir / "style.css"
        style_path.write_text(self.style_css)

HTMLReport._save_report = _save_report_patched
```

**Comment by nck974** [comment]
I'm also getting some breaking changes on code that I had: But for this specific issue I can confirm it seems to solve the utf8 issues I was having in the report:
![image](https://user-images.githubusercontent.com/18548911/224428628-6e77ea1e-d900-4adf-abba-1c2db3dc665b.png)

**Comment by BeyondEvil** [comment]
> I'm also getting some breaking changes on code that I had: But for this specific issue I can confirm it seems to solve the utf8 issues I was having in the report: ![image](https://user-images.githubusercontent.com/18548911/224428628-6e77ea1e-d900-4adf-abba-1c2db3dc665b.png)

Nice!

Mind sharing what breaking changes you have? The more detail the better. Thank you! 🙏

**Comment by nck974** [comment]
Sure, is not related to this at all. 

I have the following code to display the screenshots I'm taking during my tests in the report:
```python
@pytest.hookimpl(hookwrapper=True)
def pytest_runtest_makereport(item):
    """
    This method takes the images in the folder of the report and writes them inside the report.
    """
    pytest_html = item.config.pluginmanager.getplugin("html")
    outcome = yield

    # Get the images to be displayed inside the report
    report = outcome.get_result()
    extra = getattr(report, "extra", [])
    if report.when == "call":

        node_id = item.funcargs['request'].node.nodeid

        # Get output directory
        directory = _get_report_folder()

        # Extract images for current tc
        for file in os.listdir(directory):
            if re.search(re.escape(f'{node_id}_'), file):
                image = os.path.join(directory, file)
                with open(image, "rb") as image_file:
                    screenshot = base64.b64encode(image_file.read())
                    extra.append(pytest_html.extras.image(screenshot.decode(), ''))

                # Remove as it is already saved
                try:
                    os.remove(image)
                except OSError:
                    pass

        report.extra = extra
```

In the new version it throws:
```python

INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "<my_path>\.venv\lib\site-packages\_pytest\main.py", line 270, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "<my_path>\.venv\lib\site-packages\_pytest\main.py", line 324, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "<my_path>\.venv\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "<my_path>\.venv\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "<my_path>\.venv\lib\site-packages\pluggy\_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "<my_path>\.venv\lib\site-packages\pluggy\_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "<my_path>\.venv\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "<my_path>\.venv\lib\site-packages\_pytest\main.py", line 349, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "<my_path>\.venv\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "<my_path>\.venv\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "<my_path>\.venv\lib\site-packages\pluggy\_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "<my_path>\.venv\lib\site-packages\pluggy\_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "<my_path>\.venv\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "<my_path>\.venv\lib\site-packages\_pytest\runner.py", line 112, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "<my_path>\.venv\lib\site-packages\_pytest\runner.py", line 131, in runtestprotocol
INTERNALERROR>     reports.append(call_and_report(item, "call", log))
INTERNALERROR>   File "<my_path>\.venv\lib\site-packages\_pytest\runner.py", line 222, in call_and_report
INTERNALERROR>     report: TestReport = hook.pytest_runtest_makereport(item=item, call=call)
INTERNALERROR>   File "<my_path>\.venv\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "<my_path>\.venv\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "<my_path>\.venv\lib\site-packages\pluggy\_callers.py", line 55, in _multicall
INTERNALERROR>     gen.send(outcome)
INTERNALERROR>   File "<my_path>\conftest.py", line 76, in pytest_runtest_makereport
INTERNALERROR>     extra.append(pytest_html.extras.image(screenshot.decode(), ''))
INTERNALERROR> AttributeError: 'function' object has no attribute 'image'

```

**Comment by BeyondEvil** [comment]
Interesting.

Mind adding some info to the issue that I created? For instance, what the use case is?

Seems like we should be able to make it easier to add additional screenshots.

**Comment by freetomik** [comment]
Tried without patch (friday evening mistake) and it works correctly 👌
![obrazek](https://user-images.githubusercontent.com/5520368/224652505-7f069fde-8993-487e-beb1-291403e54350.png)

**Comment by BeyondEvil** [comment]
Excellent! 🥳 

Feel free to close this issue if you're satisified.

**Comment by freetomik** [comment]
Great, thank you for fix!
