### ISSUE TITLE
py.xml 

### ISSUE THREAD

**Issue by roni9826** [pytest-dev/pytest-html#679]
Import "py.xml" could not be resolved from source. Now I have no idea how to make it work. I am fairly a beginner in this and I had seen a previous issue on github regards to this https://github.com/microsoft/pylance-release/issues/2357 

Can anyone clarify how to make it work. My venv for the project is on Python version - 3.11.3

**Comment by fruch** [comment]
I can confirm it was failing on `pytest-html==3.1.1` and working with `pytest-html==3.2.0`

**Comment by fruch** [comment]
the exception for whom is gonna look for this failure:
```
Traceback (most recent call last):
  File "/home/fruch/.pyenv/versions/scylla-dtest-3.11.3/bin/pytest", line 8, in <module>
    sys.exit(console_main())
             ^^^^^^^^^^^^^^
  File "/home/fruch/.pyenv/versions/scylla-dtest-3.11.3/lib/python3.11/site-packages/_pytest/config/__init__.py", line 189, in console_main
    code = main()
           ^^^^^^
  File "/home/fruch/.pyenv/versions/scylla-dtest-3.11.3/lib/python3.11/site-packages/_pytest/config/__init__.py", line 147, in main
    config = _prepareconfig(args, plugins)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fruch/.pyenv/versions/scylla-dtest-3.11.3/lib/python3.11/site-packages/_pytest/config/__init__.py", line 328, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fruch/.pyenv/versions/scylla-dtest-3.11.3/lib/python3.11/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fruch/.pyenv/versions/scylla-dtest-3.11.3/lib/python3.11/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fruch/.pyenv/versions/scylla-dtest-3.11.3/lib/python3.11/site-packages/pluggy/_callers.py", line 55, in _multicall
    gen.send(outcome)
  File "/home/fruch/.pyenv/versions/scylla-dtest-3.11.3/lib/python3.11/site-packages/_pytest/helpconfig.py", line 103, in pytest_cmdline_parse
    config: Config = outcome.get_result()
                     ^^^^^^^^^^^^^^^^^^^^
  File "/home/fruch/.pyenv/versions/scylla-dtest-3.11.3/lib/python3.11/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/fruch/.pyenv/versions/scylla-dtest-3.11.3/lib/python3.11/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fruch/.pyenv/versions/scylla-dtest-3.11.3/lib/python3.11/site-packages/_pytest/config/__init__.py", line 1075, in pytest_cmdline_parse
    self.parse(args)
  File "/home/fruch/.pyenv/versions/scylla-dtest-3.11.3/lib/python3.11/site-packages/_pytest/config/__init__.py", line 1425, in parse
    self._preparse(args, addopts=addopts)
  File "/home/fruch/.pyenv/versions/scylla-dtest-3.11.3/lib/python3.11/site-packages/_pytest/config/__init__.py", line 1305, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/home/fruch/.pyenv/versions/scylla-dtest-3.11.3/lib/python3.11/site-packages/pluggy/_manager.py", line 287, in load_setuptools_entrypoints
    plugin = ep.load()
             ^^^^^^^^^
  File "/home/fruch/.pyenv/versions/3.11.3/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fruch/.pyenv/versions/3.11.3/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/home/fruch/.pyenv/versions/scylla-dtest-3.11.3/lib/python3.11/site-packages/_pytest/assertion/rewrite.py", line 178, in exec_module
    exec(co, module.__dict__)
  File "/home/fruch/.pyenv/versions/scylla-dtest-3.11.3/lib/python3.11/site-packages/pytest_html/plugin.py", line 9, in <module>
    from .html_report import HTMLReport
  File "/home/fruch/.pyenv/versions/scylla-dtest-3.11.3/lib/python3.11/site-packages/_pytest/assertion/rewrite.py", line 178, in exec_module
    exec(co, module.__dict__)
  File "/home/fruch/.pyenv/versions/scylla-dtest-3.11.3/lib/python3.11/site-packages/pytest_html/html_report.py", line 11, in <module>
    from py.xml import html
ModuleNotFoundError: No module named 'py.xml'; 'py' is not a package
```

**Comment by fruch** [comment]
https://github.com/pytest-dev/pytest-html/commit/00740f5e262c572b08000bbbc5f04faeb4e6d73c is the missing part.

BTW seems like master doesn't use `py` anymore (or at least doesn't have a dependency on it)

**Comment by BeyondEvil** [comment]
Upgrading to v4 fixes this.
