### ISSUE TITLE
Need a method to process the generated report

### ISSUE THREAD

**Issue by srujanred** [pytest-dev/pytest-html#93]
With the existing implementation, we can only generate and save report to local disk. It will be more useful if we have a method which can be called after the saving the file on disk (Like allowing user to upload the test reports once the test completes.).

In my case, i wanted to upload the generated html report to hp alm. i tried adding this code in autouse fixtures with both module and session scopes, but nothing worked because generate and save reports were called just before exiting the run. 
There is a function `HTMLReport::pytest_sessionfinish(self, session)` which can do this job. But i'm not sure how to get the session var.

**Comment by nicoddemus** [comment]
`pytest_sessionfinish` is a standard pytest plugin, so you can write a [hook wrapper](http://doc.pytest.org/en/latest/writing_plugins.html#hookwrapper-executing-around-other-hooks):

```python
@pytest.hookimpl(hookwrapper=True)
def pytest_sessionfinish(session):
    yield 
    upload_generated_html_file_to_somewhere(session)
```

You might be able to obtain the filename from the session object, but I'm not sure about the details.

**Comment by srujanred** [comment]
Thanks for quick response. The above hook is getting executed for each run. I'm looking for a way to call my report processing functions just after saving the report to disk. 

I found a workaround with [atexit](https://docs.python.org/2/library/atexit.html). I added report upload related stuff in atexit function, and the solution is working fine.


`C:\TAUT\MyProject>py.test Training_test.py
============================= test session starts =============================
platform win32 -- Python 2.7.10, pytest-3.0.4, py-1.4.31, pluggy-0.4.0
rootdir: C:\TAUT\MyProject, inifile: pytest.ini
plugins: html-1.11.0
collected 2 items 

Training_test.py ..

 generated html file: C:\Users\AppData\Local\Temp\pppytest-report.html
========================== 2 passed in 20.51 seconds ==========================
Uploading report to ALM...

C:\TAUT\MyProject>`

**Comment by nicoddemus** [comment]
> The above hook is getting executed for each run. I'm looking for a way to call my report processing functions just after saving the report to disk.

What do you mean by "each run"? Each test or each test session? 

`pytest_sessionfinish` seems to be the perfect choice, because it is at that moment that [pytest-html saves the report](https://github.com/pytest-dev/pytest-html/blob/master/pytest_html/plugin.py#L458).

**Comment by srujanred** [comment]
Sorry for the type. I meant each "call" ( for each test_* function). 
Also, i need request object for getting the object of HTMLReport. 


```
from _pytest._pluggy import HookspecMarker
hookspec = HookspecMarker("pytest")

@pytest.hookspec(hookwrapper=True)
def pytest_sessionfinish(session, exitstatus):
    print "uploading attachment"
    alm.upload_attachment()
```
```
C:\Python27\python.exe "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.1.4\helpers\pycharm\pytestrunner.py" -p pytest_teamcity C:/TAUT/MyProject/Training_test.py
Testing started at 18:05 ...
Connecting to QC..
Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.1.4\helpers\pycharm\pytestrunner.py", line 60, in <module>
    main()
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.1.4\helpers\pycharm\pytestrunner.py", line 34, in main
    pluginmanager=_pluginmanager, args=args)
  File "C:\Python27\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 745, in __call__
Logged in
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "C:\Python27\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 339, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Python27\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 334, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "C:\Python27\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 613, in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
  File "C:\Python27\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 250, in _wrapped_call
    wrap_controller.send(call_outcome)
  File "C:\Python27\lib\site-packages\_pytest\helpconfig.py", line 32, in pytest_cmdline_parse
    config = outcome.get_result()
  File "C:\Python27\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 280, in get_result
    _reraise(*ex)  # noqa
  File "C:\Python27\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 265, in __init__
    self.result = func()
  File "C:\Python27\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 614, in execute
    res = hook_impl.function(*args)
  File "C:\Python27\lib\site-packages\_pytest\config.py", line 882, in pytest_cmdline_parse
    self.parse(args)
  File "C:\Python27\lib\site-packages\_pytest\config.py", line 1038, in parse
    self._preparse(args, addopts=addopts)
  File "C:\Python27\lib\site-packages\_pytest\config.py", line 1009, in _preparse
    args=args, parser=self._parser)
  File "C:\Python27\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 745, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "C:\Python27\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 339, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Python27\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 334, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "C:\Python27\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 613, in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
  File "C:\Python27\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 254, in _wrapped_call
    return call_outcome.get_result()
  File "C:\Python27\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 280, in get_result
    _reraise(*ex)  # noqa
  File "C:\Python27\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 265, in __init__
    self.result = func()
  File "C:\Python27\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 614, in execute
    res = hook_impl.function(*args)
  File "C:\Python27\lib\site-packages\_pytest\config.py", line 928, in pytest_load_initial_conftests
    self.pluginmanager._set_initial_conftests(early_config.known_args_namespace)
  File "C:\Python27\lib\site-packages\_pytest\config.py", line 284, in _set_initial_conftests
    self._try_load_conftest(anchor)
  File "C:\Python27\lib\site-packages\_pytest\config.py", line 290, in _try_load_conftest
    self._getconftestmodules(anchor)
  File "C:\Python27\lib\site-packages\_pytest\config.py", line 304, in _getconftestmodules
    clist = self._getconftestmodules(path.dirpath())
  File "C:\Python27\lib\site-packages\_pytest\config.py", line 315, in _getconftestmodules
    mod = self._importconftest(conftestpath)
  File "C:\Python27\lib\site-packages\_pytest\config.py", line 340, in _importconftest
    raise ConftestImportFailure(conftestpath, sys.exc_info())
_pytest.config.ConftestImportFailure: TypeError("__call__() got an unexpected keyword argument 'hookwrapper'",)
  File "C:\Python27\lib\site-packages\_pytest\assertion\rewrite.py", line 212, in load_module
    py.builtin.exec_(co, mod.__dict__)
  File "C:\Python27\lib\site-packages\py\_builtin.py", line 221, in exec_
    exec2(obj, globals, locals)
  File "<string>", line 7, in exec2
  File "C:\TAUT\MyProject\conftest.py", line 82, in <module>
    @pytest.hookspec(hookwrapper=True)

Uploading testreport to ALM...

Process finished with exit code 1
Empty test suite.
about:blank
```

**Comment by srujanred** [comment]
Added below code, and its getting executed before generating html report.

```
@pytest.hookimpl(hookwrapper=True)
def pytest_sessionfinish(session):
    yield
    print " Uploading..."
    alm.upload_attachment()
```

```
C:\Python27\python.exe "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.1.4\helpers\pycharm\pytestrunner.py" -p pytest_teamcity C:/TAUT/MyProject/Training_test.py "-k test_versions"
Testing started at 18:12 ...
Connecting to QC..
Logged in
============================= test session starts =============================
platform win32 -- Python 2.7.10, pytest-3.0.4, py-1.4.31, pluggy-0.4.0
rootdir: C:\TAUT\MyProject, inifile: pytest.ini
plugins: html-1.11.0
missing netsnmp module, snmp not available
collected 3 items

..\..\..\..\..\..\TAUT\MyProject\Mosaic_CP_System_GFast_gfast_profile_100down_100up_Profile_Training_test.py 
Executing :test_versions
PA version (1.531) check passed.
. **Uploading..** <-- Call from hook


 generated html file: C:\Users\sbenjara\AppData\Local\Temp\pppytest-report.html 
============================= 2 tests deselected ==============================
=================== 1 passed, 2 deselected in 26.26 seconds ===================
Uploading testreport to ALM...  <--Call from atexit

Process finished with exit code 0
```

**Comment by nicoddemus** [comment]
What happens if you do this?

```python
@pytest.hookimpl(hookwrapper=True)
def pytest_sessionfinish(session):
    yield
    print "file exists:", os.path.isfile('C:\Users\sbenjara\AppData\Local\Temp\pppytest-report.html')
    alm.upload_attachment()
```

It is just that the `generated html file` message is displayed after the html report has been generated.

**Comment by davehunt** [comment]
I believe @karandesai-96 does something similar, which is why he refactored generate and save in pull request https://github.com/pytest-dev/pytest-html/pull/57. Perhaps another approach might be to add a custom hook for saving the report? For what it's worth, I usually leave the publishing of these files outside of pytest. For example, a post-build step in your continuous integration.

**Comment by srujanred** [comment]
Thanks Oliveira, the code you posted is perfectly working.
 -Thanks.
