### ISSUE TITLE
UnicodeEncodeError when creating detailed/fail report for pytest-selenium test run

### ISSUE THREAD

**Issue by axinom-raido** [pytest-dev/pytest-html#98]
Hi! 
Stumbled upon a problem when attempting to generate html reports for my selenium tests (in pytest), that I don't seem to be able to resolve.
When a test fails or if I increase the selenium debug level (by "_selenium_capture_debug = always_") I receive an error (see console output below). Any kind of help is much appreciated.

For the sake of clarity I created an example test that results in same error and should be easily reproducible:
_pytest.ini_
```
[pytest]
selenium_capture_debug = always
```

_test_google.py_
```
def test_htmlreporttesting(selenium):
    selenium.get("https://google.com")
    selenium.find_element_by_name('q').send_keys("error")
    selenium.find_element_by_name('btnG').click()
```
**Result from console**
```
F:\Automation\PyTest\PyTest_Google>pytest --driver Chrome --html Report.html
============================= test session starts =============================
platform win32 -- Python 3.5.2, pytest-3.0.5, py-1.4.32, pluggy-0.4.0
driver: Chrome
sensitiveurl: .*
rootdir: F:\Automation\PyTest\PyTest_Google, inifile: pytest.ini
plugins: base-url-1.2.0, html-1.13.0, selenium-1.7.0, variables-1.4, xdist-1.15.0
collected 1 items

test_google.py .
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "c:\program files\python35\lib\site-packages\_pytest\main.py", line 98, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "c:\program files\python35\lib\site-packages\_pytest\main.py", line 133, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "c:\program files\python35\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 745, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "c:\program files\python35\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 339, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "c:\program files\python35\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 334, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "c:\program files\python35\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 614, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "c:\program files\python35\lib\site-packages\_pytest\main.py", line 154, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "c:\program files\python35\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 745, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "c:\program files\python35\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 339, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "c:\program files\python35\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 334, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "c:\program files\python35\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 613, in execute
INTERNALERROR>     return _wrapped_call(hook_impl.function(*args), self.execute)
INTERNALERROR>   File "c:\program files\python35\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 254, in _wrapped_call
INTERNALERROR>     return call_outcome.get_result()
INTERNALERROR>   File "c:\program files\python35\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 279, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "c:\program files\python35\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 265, in __init__
INTERNALERROR>     self.result = func()
INTERNALERROR>   File "c:\program files\python35\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 614, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "c:\program files\python35\lib\site-packages\_pytest\runner.py", line 66, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "c:\program files\python35\lib\site-packages\_pytest\runner.py", line 79, in runtestprotocol
INTERNALERROR>     reports.append(call_and_report(item, "call", log))
INTERNALERROR>   File "c:\program files\python35\lib\site-packages\_pytest\runner.py", line 137, in call_and_report
INTERNALERROR>     hook.pytest_runtest_logreport(report=report)
INTERNALERROR>   File "c:\program files\python35\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 745, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "c:\program files\python35\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 339, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "c:\program files\python35\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 334, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "c:\program files\python35\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 614, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "c:\program files\python35\lib\site-packages\pytest_html\plugin.py", line 453, in pytest_runtest_logreport
INTERNALERROR>     self.append_passed(report)
INTERNALERROR>   File "c:\program files\python35\lib\site-packages\pytest_html\plugin.py", line 268, in append_passed
INTERNALERROR>     self._appendrow('Passed', report)
INTERNALERROR>   File "c:\program files\python35\lib\site-packages\pytest_html\plugin.py", line 254, in _appendrow
INTERNALERROR>     self.logfile)
INTERNALERROR>   File "c:\program files\python35\lib\site-packages\pytest_html\plugin.py", line 128, in __init__
INTERNALERROR>     self.append_extra_html(extra, extra_index, test_index)
INTERNALERROR>   File "c:\program files\python35\lib\site-packages\pytest_html\plugin.py", line 208, in append_extra_html
INTERNALERROR>     extra.get('extension'))
INTERNALERROR>   File "c:\program files\python35\lib\site-packages\pytest_html\plugin.py", line 162, in create_asset
INTERNALERROR>     f.write(content)
INTERNALERROR>   File "c:\program files\python35\lib\encodings\cp1252.py", line 19, in encode
INTERNALERROR>     return codecs.charmap_encode(input,self.errors,encoding_table)[0]
INTERNALERROR> UnicodeEncodeError: 'charmap' codec can't encode characters in position 104329-104335: character maps to <undefined>

========================== 1 passed in 9.05 seconds ===========================
```

**Comment by davehunt** [comment]
I suspect there are characters in the page source that are causing issues during encoding. If you try running with the environment variable `SELENIUM_EXCLUDE_DEBUG=html` this should confirm it. I'll look into this when I get some time, but if anyone else wants to pick it up, that would be great!

**Comment by axinom-raido** [comment]
I ran the example test through with `SELENIUM_EXCLUDE_DEBUG=html:logs:screenshot` added to _pytest.ini_ - same result.

**Comment by einsteinsfool** [comment]
I got the same error and got around it by setting LC_ALL variable to 'en_US.utf8' with this command on Linux:
`export LC_ALL='en_US.utf8'`
To reproduce this bug you may set LC_ALL to 'C'.

**Comment by axinom-raido** [comment]
Grateful for the comment. Unfortunately don't know if or how I can use it since I encountered the issue on Windows 10. But maybe it can help to shed some light onto the essence of the issue, and at least it helps Linux users.

**Comment by einsteinsfool** [comment]
Well, LC_ALL is the environment variable that overrides all the other localisation settings. So perhaps changing your system language to English might help, if you're willing to do that.
Follow this tutorial, if you're interested:
https://www.howtogeek.com/232659/how-to-change-the-display-language-in-windows-10

**Comment by axinom-raido** [comment]
Thanks for the effort, but my system language is already English (United States), so that's not the case.

**Comment by einsteinsfool** [comment]
Perhaps try writing in cmd one of these commands:
`set LANG=English_USA.1252`
`set LANG=.fglutf8`
...as presented [here](http://4js.com/online_documentation/fjs-fgl-manual-html/c_fgl_localization_017.html).

**Comment by davehunt** [comment]
I'll release 1.14.0 soon (maybe today) with this fix.

**Comment by axinom-raido** [comment]
Thank you for the fix, much appreciated.

**Comment by chennareddy08** [comment]
1.21 version i am getting above error
